# Generated by Django 4.1 on 2022-08-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_date',
            new_name='birthDate',
        ),
    ]
