"""
------------------------------------------------------------
--------String methods Connect and separate strings --------
------------------------------------------------------------

The join() function returns the string generated by joining the strings of an iterable object.
The split() function splits a string into a list of strings based on a specified separator.
The splitlines() function splits a string into a list of lines.

"""

print("--------------------------------------------------")
# join()
list = ['Hello', 'World']
print(' '.join(list))
print('-'.join(list))
print('ABC'.join(list))
print(type(' '.join(list)))

print("--------------------------------------------------")
# split()
test = 'Hello world'
print(test.split(' '))

test = 'MyABCNameABCIsABCJamal'
print(test.split('ABC'))

test = """Hello
How are you?
Thanks I Am Fine"""
print(test.split('\n'))

print("--------------------------------------------------")
# splitlines()

test = """Hello
How are you?
Thanks I Am Fine"""
print(test.splitlines())

test = 'Hello\nHow are You?\nI Am Good thanks'
print(test.splitlines())